package litun.uxinnovator.ui.theme

import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// Dark scheme — exact values from Stitch design system ("The Digital Atrium")
// ---------------------------------------------------------------------------
val DarkPrimary = Color(0xFFBAC3FF)
val DarkOnPrimary = Color(0xFF08218A)
val DarkPrimaryContainer = Color(0xFF3F51B5)
val DarkOnPrimaryContainer = Color(0xFFCACFFF)
val DarkPrimaryFixed = Color(0xFFDEE0FF)
val DarkPrimaryFixedDim = Color(0xFFBAC3FF)
val DarkOnPrimaryFixed = Color(0xFF00105C)
val DarkOnPrimaryFixedVariant = Color(0xFF293CA0)
val DarkInversePrimary = Color(0xFF4355B9)

val DarkSecondary = Color(0xFFBAC3FF)
val DarkOnSecondary = Color(0xFF15267B)
val DarkSecondaryContainer = Color(0xFF2F3F92)
val DarkOnSecondaryContainer = Color(0xFFA3B0FF)
val DarkSecondaryFixed = Color(0xFFDEE0FF)
val DarkSecondaryFixedDim = Color(0xFFBAC3FF)
val DarkOnSecondaryFixed = Color(0xFF00105B)
val DarkOnSecondaryFixedVariant = Color(0xFF2F3F92)

val DarkTertiary = Color(0xFFFFB784)
val DarkOnTertiary = Color(0xFF502500)
val DarkTertiaryContainer = Color(0xFF8F4700)
val DarkOnTertiaryContainer = Color(0xFFFFC7A2)
val DarkTertiaryFixed = Color(0xFFFFDCC6)
val DarkTertiaryFixedDim = Color(0xFFFFB784)
val DarkOnTertiaryFixed = Color(0xFF301400)
val DarkOnTertiaryFixedVariant = Color(0xFF713700)

val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

val DarkBackground = Color(0xFF121416)
val DarkOnBackground = Color(0xFFE2E2E5)
val DarkSurface = Color(0xFF121416)
val DarkOnSurface = Color(0xFFE2E2E5)
val DarkSurfaceVariant = Color(0xFF333537)
val DarkOnSurfaceVariant = Color(0xFFC5C5D4)
val DarkSurfaceTint = Color(0xFFBAC3FF)
val DarkSurfaceBright = Color(0xFF37393B)
val DarkSurfaceDim = Color(0xFF121416)
val DarkSurfaceContainerLowest = Color(0xFF0C0E10)
val DarkSurfaceContainerLow = Color(0xFF1A1C1E)
val DarkSurfaceContainer = Color(0xFF1E2022)
val DarkSurfaceContainerHigh = Color(0xFF282A2C)
val DarkSurfaceContainerHighest = Color(0xFF333537)

val DarkOutline = Color(0xFF8F909E)
val DarkOutlineVariant = Color(0xFF454652)
val DarkInverseSurface = Color(0xFFE2E2E5)
val DarkInverseOnSurface = Color(0xFF2F3133)
val DarkScrim = Color(0xFF000000)

// ---------------------------------------------------------------------------
// Light scheme — M3 tonal palette derived from seed #3F51B5 (Deep Indigo)
// ---------------------------------------------------------------------------
val LightPrimary = Color(0xFF4355B9)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDEE0FF)
val LightOnPrimaryContainer = Color(0xFF00105C)
val LightInversePrimary = Color(0xFFBAC3FF)

val LightSecondary = Color(0xFF595D91)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDFE0FF)
val LightOnSecondaryContainer = Color(0xFF141649)

val LightTertiary = Color(0xFF7C5800)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCC6)
val LightOnTertiaryContainer = Color(0xFF301400)

val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

val LightBackground = Color(0xFFFDF8FF)
val LightOnBackground = Color(0xFF1A1B1E)
val LightSurface = Color(0xFFFDF8FF)
val LightOnSurface = Color(0xFF1A1B1E)
val LightSurfaceVariant = Color(0xFFE3E1EC)
val LightOnSurfaceVariant = Color(0xFF46464F)
val LightSurfaceTint = Color(0xFF4355B9)
val LightSurfaceBright = Color(0xFFFDF8FF)
val LightSurfaceDim = Color(0xFFDDD8E3)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF7F2FC)
val LightSurfaceContainer = Color(0xFFF1ECF6)
val LightSurfaceContainerHigh = Color(0xFFEBE6F0)
val LightSurfaceContainerHighest = Color(0xFFE5E1EB)

val LightOutline = Color(0xFF777680)
val LightOutlineVariant = Color(0xFFC7C5D0)
val LightInverseSurface = Color(0xFF303033)
val LightInverseOnSurface = Color(0xFFF3EFF4)
val LightScrim = Color(0xFF000000)
